import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Veyra Cinematic Design System
        'on-tertiary-fixed-variant': '#930007',
        'primary-fixed-dim': '#d0bcff',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#c8c6c8',
        'tertiary-container': '#ff5447',
        'error-container': '#93000a',
        'outline': '#958ea0',
        'surface': '#131314',
        'surface-container-low': '#1c1b1c',
        'inverse-primary': '#6d3bd7',
        'surface-dim': '#131314',
        'secondary-fixed': '#e5e1e4',
        'on-tertiary-container': '#5c0002',
        'inverse-on-surface': '#313031',
        'on-secondary-fixed-variant': '#474649',
        'tertiary-fixed-dim': '#ffb4aa',
        'on-tertiary-fixed': '#410001',
        'on-primary-fixed': '#23005c',
        'secondary': '#c8c6c8',
        'on-primary-container': '#340080',
        'background': '#0A0A0B',
        'surface-container': '#201f20',
        'on-surface': '#e5e2e3',
        'primary-container': '#a078ff',
        'tertiary': '#ffb4aa',
        'surface-bright': '#3a393a',
        'surface-variant': '#353436',
        'surface-container-lowest': '#0e0e0f',
        'on-secondary': '#303032',
        'on-secondary-fixed': '#1b1b1d',
        'on-primary-fixed-variant': '#5516be',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'inverse-surface': '#e5e2e3',
        'secondary-container': '#474649',
        'primary': '#d0bcff',
        'tertiary-fixed': '#ffdad5',
        'surface-tint': '#d0bcff',
        'on-primary': '#3c0091',
        'on-error': '#690005',
        'outline-variant': '#494454',
        'on-secondary-container': '#b7b4b7',
        'on-tertiary': '#690003',
        'primary-fixed': '#e9ddff',
        'on-background': '#e5e2e3',
        'on-surface-variant': '#cbc3d7',
        'error': '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '80px',
        'grid-margin-mobile': '20px',
        'grid-margin-desktop': '64px',
        'container-max': '1440px',
        'content-gap': '24px',
        'gutter': '24px',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
